{% set name = "cylc-rose" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0bb68be9515f9b4b8f65d9b8d6eaae2aac8326de6f4704004c4003d420461824

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed

requirements:
  host:
    - __unix
    - python >=3.7
    - pip
  run:
    - __unix
    - python >=3.7
    - metomi-rose-base >=2.3,<2.4
    - cylc-flow-base >=8.3,<8.4
    - metomi-isodatetime
    - ansimarkup
    - jinja2

test:
  imports:
    - cylc.flow
    - cylc.rose
    - metomi.rose
  commands:
    - PAGER=cat rose stem --help

about:
  home: https://github.com/cylc/cylc-rose
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: Cylc Rose is the bridge between Rose suite configurations and Cylc workflows.
  description: |
    Cylc Rose is a replacement for the rose suite-run command (present in Rose
    versions 2019.01 and earlier). It reads the rose-suite.conf file and
    performs the required actions.
  doc_url: https://cylc.github.io/cylc-doc/latest/html/plugins/cylc-rose.html
  dev_url: https://github.com/cylc/cylc-rose

extra:
  recipe-maintainers:
    - oliver-sanders
    - wxtim
    - metronnie
