{% set name = "cylc-rose" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 280449bc8d2bc0426468b13c0f0602e8ca231c690ece5444af5bd55f6be60284

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed

requirements:
  host:
    - __unix
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - __unix
    - python >={{ python_min }}
    - metomi-rose-base >=2.4,<2.5
    - cylc-flow-base >=8.4,<8.5
    - metomi-isodatetime
    - ansimarkup
    - jinja2

test:
  requires:
    - python {{ python_min }}
  imports:
    - cylc.flow
    - cylc.rose
    - metomi.rose
  commands:
    - PAGER=cat rose stem --help

about:
  home: https://github.com/cylc/cylc-rose
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: Cylc Rose is the bridge between Rose suite configurations and Cylc workflows.
  description: |
    Cylc Rose is a replacement for the rose suite-run command (present in Rose
    versions 2019.01 and earlier). It reads the rose-suite.conf file and
    performs the required actions.
  doc_url: https://cylc.github.io/cylc-doc/latest/html/plugins/cylc-rose.html
  dev_url: https://github.com/cylc/cylc-rose

extra:
  recipe-maintainers:
    - oliver-sanders
    - wxtim
    - metronnie
