{% set name = "cylc-rose" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/fb/b7/b0595e10bee032c73e24909623ff359e423aefb76c35be1c2e51bb147af5/cylc_rose-{{ version }}.tar.gz
  sha256: ec2ddcb410d65d233743e5646d0aa360bef7ff28aa89eac111a2f4365efccade

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed

requirements:
  host:
    - __unix
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - __unix
    - python >={{ python_min }}
    - metomi-rose-base >=2.6,<2.8
    - cylc-flow-base >=8.6,<8.7
    - metomi-isodatetime
    - ansimarkup
    - jinja2

test:
  requires:
    - python {{ python_min }}
  imports:
    - cylc.flow
    - cylc.rose
    - metomi.rose
  commands:
    - PAGER=cat rose stem --help

about:
  home: https://github.com/cylc/cylc-rose
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: Cylc Rose is the bridge between Rose suite configurations and Cylc workflows.
  description: |
    Cylc Rose is a replacement for the rose suite-run command (present in Rose
    versions 2019.01 and earlier). It reads the rose-suite.conf file and
    performs the required actions.
  doc_url: https://cylc.github.io/cylc-doc/latest/html/plugins/cylc-rose.html
  dev_url: https://github.com/cylc/cylc-rose

extra:
  recipe-maintainers:
    - oliver-sanders
    - wxtim
    - metronnie
